#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend sawlew.tech
    timeout client  30000
    bind 0:80
    default_backend sawlew.tech_backend

backend sawlew.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 217913-web-01 35.153.16.246:80 check
    server 217913-web-02 52.201.186.77:80 check
EOT

sudo service haproxy restart
